Console.WriteLine("1	PALMEIRAS");	
Console.WriteLine("2	FLAMENGO");	
Console.WriteLine("3	INTERNACIONAL");
Console.WriteLine("4	GRÊMIO");	
Console.WriteLine("5	SÃO PAULO");	
Console.WriteLine("6	ATLÉTICO-MG");
Console.WriteLine("7	ATHLETICO");	
Console.WriteLine("8	CRUZEIRO");	
Console.WriteLine("9	BOTAFOGO");	
Console.WriteLine("10	SANTOS	");
Console.WriteLine("10	SANTOS	");
Console.WriteLine("11	BAHIA		");
Console.WriteLine("12	FLUMINENSE	");
Console.WriteLine("13	CORINTHIANS	");
Console.WriteLine("14	CHAPECOENSE	");
Console.WriteLine("15	CEARÁ		");
Console.WriteLine("16	VASCO		");
Console.WriteLine("17	SPORT		");
Console.WriteLine("18	AMÉRICA-MG	");
Console.WriteLine("19	VITÓRIA);		");
Console.WriteLine("20      PARANÁ");